import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire (see note below)

Future<void> bootstrapFirebase() async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}
